"""API key authorizer handler for HTTP API Gateway.

Validates the API key from the Authorization header and returns a
SimpleAuthorizerResult with tenant_id context.

Key resolution order:
1. Environment variable test keys (fast, no network, for development).
2. DynamoDB users table lookup via GSI on api_key_hash (production keys
   generated by the dashboard self-service flow).

SECURITY: Never log API keys or full authorization headers.
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
import time
from datetime import datetime, timezone
from typing import Any

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

# API key → tenant mapping.
# Load test keys from environment. Format: "key1:tenant1,key2:tenant2"
# Falls back to the MNEMORA_TEST_API_KEY env var for single-key dev setups.
_TEST_KEYS: dict[str, str] = {}


def _load_api_keys() -> dict[str, str]:
    """Load API key → tenant mappings from environment variables.

    Supports two env vars:
    - MNEMORA_API_KEYS: Comma-separated "key:tenant" pairs.
    - MNEMORA_TEST_API_KEY + MNEMORA_TEST_TENANT: Single key for development.

    Returns:
        Dict mapping SHA-256 key hashes to tenant IDs.
    """
    keys: dict[str, str] = {}

    # Multi-key format: "key1:tenant1,key2:tenant2"
    api_keys_env = os.environ.get("MNEMORA_API_KEYS", "")
    if api_keys_env:
        for pair in api_keys_env.split(","):
            pair = pair.strip()
            if ":" in pair:
                raw_key, tenant = pair.split(":", 1)
                key_hash = hashlib.sha256(raw_key.strip().encode()).hexdigest()
                keys[key_hash] = tenant.strip()

    # Single-key dev shortcut
    test_key = os.environ.get("MNEMORA_TEST_API_KEY", "")
    test_tenant = os.environ.get("MNEMORA_TEST_TENANT", "dev-tenant")
    if test_key:
        key_hash = hashlib.sha256(test_key.encode()).hexdigest()
        keys[key_hash] = test_tenant

    return keys


# Load once at module init (Lambda cold start).
_TEST_KEYS = _load_api_keys()


def handler(event: dict[str, Any], context: Any) -> dict[str, Any]:
    """Handle Lambda authorizer requests for HTTP API Gateway.

    Expects Simple response format (HTTP API v2 payload).

    Args:
        event: Authorizer event with headers and requestContext.
        context: Lambda execution context.

    Returns:
        SimpleAuthorizerResult: {"isAuthorized": bool, "context": {...}}.
    """
    start_time = time.time()
    request_id = event.get("requestContext", {}).get("requestId", "unknown")

    logger.info(
        json.dumps(
            {
                "request_id": request_id,
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "path": event.get("rawPath", "unknown"),
                "method": event.get("requestContext", {})
                .get("http", {})
                .get("method", "unknown"),
                "action": "authorize",
            }
        )
    )

    api_key = _extract_api_key(event)

    if not api_key:
        logger.info(
            json.dumps(
                {
                    "request_id": request_id,
                    "action": "authorize",
                    "result": "denied",
                    "reason": "missing_key",
                    "latency_ms": round((time.time() - start_time) * 1000),
                }
            )
        )
        return _deny_response()

    tenant_id = _resolve_tenant(api_key)

    if not tenant_id:
        logger.info(
            json.dumps(
                {
                    "request_id": request_id,
                    "action": "authorize",
                    "result": "denied",
                    "reason": "invalid_key",
                    "latency_ms": round((time.time() - start_time) * 1000),
                }
            )
        )
        return _deny_response()

    logger.info(
        json.dumps(
            {
                "request_id": request_id,
                "action": "authorize",
                "result": "allowed",
                "tenant_id": tenant_id,
                "latency_ms": round((time.time() - start_time) * 1000),
            }
        )
    )

    # Fire-and-forget: increment per-tenant API call counters.
    _increment_api_calls(tenant_id)

    return {
        "isAuthorized": True,
        "context": {
            "tenantId": tenant_id,
        },
    }


def _extract_api_key(event: dict[str, Any]) -> str | None:
    """Extract API key from the Authorization header.

    Supports formats:
    - "Bearer <key>"
    - "<key>" (raw)

    Args:
        event: API Gateway authorizer event.

    Returns:
        The raw API key string, or None if not present.
    """
    headers = event.get("headers", {})
    auth_header = headers.get("authorization", "")

    if not auth_header:
        return None

    if auth_header.startswith("Bearer "):
        return auth_header[7:].strip()

    return auth_header.strip() or None


def _resolve_tenant(api_key: str) -> str | None:
    """Resolve an API key to a tenant_id.

    Checks two sources in order:
    1. Environment-variable test keys (fast, no network, for development).
    2. DynamoDB users table lookup via GSI on api_key_hash.

    Args:
        api_key: Raw API key string.

    Returns:
        tenant_id if the key is valid, None otherwise.
    """
    key_hash = hashlib.sha256(api_key.encode()).hexdigest()

    # 1. Check env-var test keys first (fast path, no network)
    tenant = _TEST_KEYS.get(key_hash)
    if tenant:
        return tenant

    # 2. DynamoDB lookup via GSI on api_key_hash
    table_name = os.environ.get("USERS_TABLE_NAME")
    if not table_name:
        return None

    try:
        client = _get_dynamo_client()
        response = client.query(
            TableName=table_name,
            IndexName="api-key-index",
            KeyConditionExpression="api_key_hash = :hash",
            ExpressionAttributeValues={":hash": {"S": key_hash}},
            Limit=1,
        )
        items = response.get("Items", [])
        if items:
            github_id = items[0]["github_id"]["S"]
            return f"github:{github_id}"
    except Exception as e:
        logger.error(
            json.dumps(
                {
                    "action": "dynamo_lookup_error",
                    "error": str(e),
                }
            )
        )

    return None


# Lazy-initialized DynamoDB client (created on first use).
_dynamo_client: Any = None


def _get_dynamo_client() -> Any:
    """Return a lazily-initialized boto3 DynamoDB client.

    Returns:
        boto3 DynamoDB low-level client.
    """
    global _dynamo_client  # noqa: PLW0603
    if _dynamo_client is None:
        import boto3

        _dynamo_client = boto3.client("dynamodb")
    return _dynamo_client


def _increment_api_calls(tenant_id: str) -> None:
    """Increment per-tenant daily and monthly API call counters.

    Stores counters on the users table keyed by github_id. Automatically
    resets the daily counter when the date changes and the monthly counter
    when the month changes.

    This is fire-and-forget: errors are logged but never block auth.

    Args:
        tenant_id: Tenant identifier (format ``github:<github_id>``).
    """
    table_name = os.environ.get("USERS_TABLE_NAME")
    if not table_name or not tenant_id.startswith("github:"):
        return

    github_id = tenant_id.removeprefix("github:")
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    month = datetime.now(timezone.utc).strftime("%Y-%m")
    client = _get_dynamo_client()

    try:
        # Happy path: same day & month — just increment.
        client.update_item(
            TableName=table_name,
            Key={"github_id": {"S": github_id}},
            UpdateExpression=(
                "SET api_calls_today = if_not_exists(api_calls_today, :zero) + :one, "
                "api_calls_month = if_not_exists(api_calls_month, :zero) + :one, "
                "last_call_date = :today, "
                "last_call_month = :month"
            ),
            ConditionExpression=(
                "(attribute_not_exists(last_call_date) OR last_call_date = :today) "
                "AND (attribute_not_exists(last_call_month) OR last_call_month = :month)"
            ),
            ExpressionAttributeValues={
                ":zero": {"N": "0"},
                ":one": {"N": "1"},
                ":today": {"S": today},
                ":month": {"S": month},
            },
        )
    except Exception as exc:
        if "ConditionalCheckFailedException" in type(exc).__name__:
            # Day or month rolled over — determine what to reset.
            try:
                resp = client.get_item(
                    TableName=table_name,
                    Key={"github_id": {"S": github_id}},
                    ProjectionExpression="last_call_month",
                )
                stored_month = (
                    resp.get("Item", {}).get("last_call_month", {}).get("S", "")
                )

                if stored_month != month:
                    # Month changed — reset both counters.
                    expr = (
                        "SET api_calls_today = :one, api_calls_month = :one, "
                        "last_call_date = :today, last_call_month = :month"
                    )
                else:
                    # Only day changed — reset daily, increment monthly.
                    expr = (
                        "SET api_calls_today = :one, "
                        "api_calls_month = if_not_exists(api_calls_month, :zero) + :one, "
                        "last_call_date = :today, last_call_month = :month"
                    )

                client.update_item(
                    TableName=table_name,
                    Key={"github_id": {"S": github_id}},
                    UpdateExpression=expr,
                    ExpressionAttributeValues={
                        ":zero": {"N": "0"},
                        ":one": {"N": "1"},
                        ":today": {"S": today},
                        ":month": {"S": month},
                    },
                )
            except Exception:
                logger.warning("Failed to reset API call counters", exc_info=True)
        else:
            logger.warning("Failed to increment API call counters", exc_info=True)


def _deny_response() -> dict[str, Any]:
    """Build a deny response for the authorizer.

    Returns:
        SimpleAuthorizerResult denying access.
    """
    return {
        "isAuthorized": False,
        "context": {},
    }
